# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/tmpfs.ramdisk/ParadigmeDeProgramare/TemaLab5/html_converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HTMLConverter(object):
    def setupUi(self, HTMLConverter):
        HTMLConverter.setObjectName("HTMLConverter")
        HTMLConverter.resize(704, 295)
        self.gridLayout = QtWidgets.QGridLayout(HTMLConverter)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path_line_edit = QtWidgets.QLineEdit(HTMLConverter)
        self.path_line_edit.setReadOnly(False)
        self.path_line_edit.setObjectName("path_line_edit")
        self.horizontalLayout.addWidget(self.path_line_edit)
        self.browse_btn = QtWidgets.QPushButton(HTMLConverter)
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout.addWidget(self.browse_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.result = QtWidgets.QTextEdit(HTMLConverter)
        self.result.setReadOnly(True)
        self.result.setProperty("sizeHint", QtCore.QSize(700, 200))
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.result)
        self.convert_btn = QtWidgets.QPushButton(HTMLConverter)
        self.convert_btn.setObjectName("convert_btn")
        self.gridLayout.addWidget(self.convert_btn)
        spacerItem = QtWidgets.QSpacerItem(124, 100, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(123, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 92, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)

        self.retranslateUi(HTMLConverter)
        QtCore.QMetaObject.connectSlotsByName(HTMLConverter)

    def retranslateUi(self, HTMLConverter):
        _translate = QtCore.QCoreApplication.translate
        HTMLConverter.setWindowTitle(_translate("HTMLConverter", "HTML Converter"))
        self.path_line_edit.setPlaceholderText(_translate("HTMLConverter", "/path/to/a/text/file"))
        self.browse_btn.setText(_translate("HTMLConverter", "Browse"))
        self.result.setPlaceholderText(_translate("HTMLConverter", "HTML Output"))
        self.convert_btn.setText(_translate("HTMLConverter", "Convert"))
